MusicApp/urls.py
from django.contrib import admin
from django.urls import path
from MusicApp import views

urlpatterns = [
    path('', views.home, name="home"),
    path('album/add/', views.AddAlbum.as_view(), name="add-album"),
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('album/detail/<int:pk>/', views.album_details, name="album-details"),
    path('album/edit/<int:pk>/', views.EditAlbum.as_view(), name="album-edit"),
    path('album/delete/<int:pk>/', views.AlbumDeleteView.as_view(), name="album-delete"),
    path('profile/details/<int:id>/', views.profile_details, name="profile-details"),
    path('profile/edit/<int:pk>/', views.UserEdit.as_view(), name="profile-edit"),
    path('profile/delete/<int:pk>/', views.ProfileDeleteView.as_view(), name="profile-delete"),
    path('album/review/<int:pk>/', views.ReviewAlbum.as_view(), name='review'),
    path('album/reviews/<int:pk>/', views.ReviewsListView.as_view(), name='review-list'),
    path('albums/', views.AlbumListView.as_view(), name='showcase'),
    path('review/<int:pk>/like/', views.like_review, name='like-review'),
    path('review/<int:pk>/dislike/', views.dislike_review, name='dislike-review'),
]

MusicSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MusicApp.urls'))
]

MusicApp/models.py
from django.db import models
from django.core.validators import RegexValidator, MinValueValidator
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group as DjangoGroup


class MyMusicAppUser(AbstractUser):
    DO_NOT_SHOW = ''
    GENDERS = [
        ('male', "Male"),
        ('female', "Female"),
        (DO_NOT_SHOW, ''),
    ]

    profile_picture = models.URLField(null=True, blank=True)
    gender = models.CharField(max_length=11, choices=GENDERS, null=True, blank=True, default=DO_NOT_SHOW)


    def get_user_name(self):
        if self.first_name and self.last_name:
            return self.first_name + ' ' + self.last_name
        elif self.first_name or self.last_name:
            return self.first_name or self.last_name
        else:
            return self.username


class Album(models.Model):
    CHOICES = [
        ("pop music", "Pop Music"),
        ("jazz music", "Jazz Music"),
        ("R&B Music", "R&B Music"),
        ("Rock Music", "Rock Music"),
        ("Country Music", "Country Music"),
        ("Dance Music", "Dance Music"),
        ("Hip Hop Music", "Hip Hop Music"),
        ("Metal Music", "Metal Music"),
        ("Other", "Other"),
    ]

    album_name = models.CharField(unique=True, max_length=30)
    artist = models.CharField(max_length=30)
    genre = models.CharField(max_length=30, choices=CHOICES)
    description = models.TextField(blank= True, null=30)
    image = models.URLField()
    price = models.FloatField(validators=[MinValueValidator(0)])
    profile = models.ForeignKey(MyMusicAppUser, on_delete=models.CASCADE)
    average_rating = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.album_name


class Review(models.Model):
    CHOICES = [
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),

    ]

    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=30)
    rating = models.CharField(choices=CHOICES, max_length=30)
    profile = models.ForeignKey(MyMusicAppUser, on_delete=models.CASCADE)


class Like(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    profile = models.ForeignKey(MyMusicAppUser, on_delete=models.CASCADE)


class Dislike(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    profile = models.ForeignKey(MyMusicAppUser, on_delete=models.CASCADE)

templates/add-album.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="createPage">

    <form {% url 'add-album' %} method="post">
        <fieldset>
            <legend>Add Album</legend>
            <div class="container">

                <!-- Form for Adding Album -->
                {% csrf_token %}
                {{ form}}
                <!-- Button for Adding Album -->
                <button class="add-album" type="submit">Add New Album</button>
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}

templates/album-delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}

 <div class="editProfile">
        <div class="edit-profile-form-container">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
                <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>

{% endblock %}

templates/album-details.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    <div class="profileDetailsMain">
        <div class="edit-profile-form-container">

            <fieldset>
                <legend>Album Details</legend>
                <div class="profileDetails">
                    <img src="{{ album.image }}" alt="No Profile Picture" class="album-image">
                    <p>Album Name: {{ album.album_name }}</p>
                    <p>Artist: {{ album.artist }}</p>
                    <p>Description: {{ album.description }}</p>
                    <p>Price: {{ album.price }}</p>
                    <p>Genre: {{ album.genre }}</p>

                </div>
            </fieldset>
            <!-- Register Button-->

            <!-- End Register Form -->


        </div>
    </div>

{% endblock %}

templates/albums-showcase.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    <h1>All Albums</h1>
    <ul class="album-list">
        {% for album in albums %}
            <li class="album-item">

                <img src="{{ album.image }}" alt="{{ album.album_name }}" class="album-image">
                <div class="album-details">
                    <h3>{{ album.album_name }} - {{ album.artist }}</h3>
                    <h3>Rating: {{ album.average_rating|floatformat:2 }} </h3>
                    <!-- Display other album details here -->
                    <div class="description-box">
                        <p>{{ album.description }}</p>
                    </div>
                    <div class="description-box">
                        <a href="{% url 'review' album.id%}">Make a review</a>
                        <a href="{% url 'album-edit' album.id%}">Edit Album</a>
                        <a href="{% url 'album-details' album.id%}">Details</a>
                        <a href="{% url 'album-delete' album.id%}">Delete Album</a>
                        <a href="{% url 'review-list' album.id%}">See All Reviews</a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    <!-- Display pagination links -->
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current-page">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Music Reviews</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header>
    <a href="{% url 'home' %}"><h1>Music Imdb</h1></a>
    <nav>

        <a href="{% url 'home' %}">Home</a>
        {% if not request.user.is_authenticated %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'register' %}">Register</a>
        {% else %}
            <a href="{% url 'add-album' %}">Add Album</a>
            <a href="{% url 'showcase' %}">Album List</a>
            <a href="{% url 'profile-details' request.user.id%}">Profile Details</a>
            <a href="{% url 'profile-edit' request.user.id%}">Edit Profile</a>
            <a href="{% url 'profile-delete' request.user.id%}">Delete Profile</a>
            <a href="{% url 'logout' %}">Logout</a>

        {% endif %}
    </nav>
</header>
    <!-- End Navigation Bar -->

    <!-- Main Content -->
<main>
    {% block content %}
    {% endblock %}
</main>
    <!-- Footer -->
<footer>
    <p>&copy; 2023 Music Reviews. All rights reserved.</p>
</footer>
<script src="{% static 'js/carousel.js' %}"></script>
</body>
</html>

templates/create-profile.html
{% extends "base.html" %}
{% load custom_filters %}
{% load static %}
{% block content %}

    <div class="registerPage">
        <div class="register-form-container">

            <!-- Start Register Form-->
            <form method="post" action="{% url 'register' %}">
                {% csrf_token %}
                <fieldset>
                    <legend>Register</legend>
                    <div class="form-fields">
                        {{ form.username.errors }}
                        {{ form.username|placeholder:'Username' }}
                        {{ form.email.errors }}
                        {{ form.email|placeholder:'Email' }}
                        {{ form.password1.errors }}
                        {{ form.password2.errors }}
                        {{ form.password1|placeholder:'Password' }}
                        {{ form.password2|placeholder:'Repeat password' }}
                    </div>
                </fieldset>
                <!-- Register Button-->
                <button class="add-album" type="submit">Register</button>
            </form>
            <!-- End Register Form -->

            <div class="second-option"><p>Have an account?
                <!-- Link to Login Page-->
                <a href="{% url 'login' %}">Log in</a></p>
            </div>
        </div>
    </div>
    <!-- End Register Section-->


{% endblock %}

templates/edit-album.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    <div class="editAlbum">
        <div class="edit-profile-form-container">

            <!-- Start Register Form-->
            <form method="post" >
                {% csrf_token %}
                <fieldset>
                    <legend>Edit Album</legend>
                    <div class="form-fields">
                        {{ form.as_p }}
                    </div>
                </fieldset>
                <!-- Register Button-->
                <button class="add-album" type="submit">Edit Album</button>
            </form>
            <!-- End Register Form -->


        </div>
    </div>
{% endblock %}

templates/edit-profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="editProfile">
        <div class="edit-profile-form-container">

            <!-- Start Register Form-->
            <form method="post" action="{% url 'profile-edit' request.user.id%}">
                {% csrf_token %}
                <fieldset>
                    <legend>Edit Profile</legend>
                    <div class="form-fields">
                        {{ form.as_p }}
                    </div>
                </fieldset>
                <!-- Register Button-->
                <button class="add-album" type="submit">Edit Profile</button>
            </form>
            <!-- End Register Form -->


        </div>
    </div>


{% endblock %}

templates/home-no-profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



    <div class="carousel-container">
        <div class="carousel">

            {% for album in albums %}
                <div class="album">
                    <div class="image-carousel">
                        <div class="image-group">
                            <img src="{{ album.image }}" alt="{{ album.album_name }}" class="carousel-image">
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
        <button class="prev-button">Previous</button>
        <button class="next-button">Next</button>
    </div>
    <script>
        var albumsData = JSON.parse('{{ albums_json|escapejs }}');
    </script>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <main>

        <!-- Start Login Section -->
        <section class="loginPage">
            <div class="form-container">
                <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <fieldset>
                        <legend>Login</legend>
                        <div class="form-fields">
                            {{ form.as_p }}
                        </div>
                        <button class="add-album" type="submit">Log in</button>
                    </fieldset>
                </form>
                <div class="second-option">
                    <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
                </div>
            </div>
        </section>
        <!-- End Login Section -->

    </main>
{% endblock %}

templates/profile-delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="editProfile">
        <div class="edit-profile-form-container">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
                <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>

{% endblock %}

templates/profile-details.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="profileDetailsMain">
        <div class="edit-profile-form-container">

            <!-- Start Register Form-->



                <legend>Profile Details</legend>
                <div class="profileDetails">
                    <img src="{{ profile.profile_picture }}" alt="No Profile Picture" class="album-image">
                    <p>First Name: {{ profile.first_name }}</p>
                    <p>Last Name: {{ profile.last_name }}</p>
                    <p>Email: {{ profile.email }}</p>
                    <p>Gender: {{ profile.gender }}</p>

                </div>

            <!-- Register Button-->

            <!-- End Register Form -->


        </div>
    </div>


{% endblock %}

templates/review-album.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<section class="createReview">
    <div class="form-container">
        <form  method="post">
            <fieldset>
                <legend>Make a Review</legend>
                <div class="form-fields">
                    <!-- Form for Adding Album -->
                    {% csrf_token %}
                    {{ form }}
                </div>
                <!-- Button for Adding Album -->
                <button class="add-album" type="submit">Submit Review</button>
            </fieldset>
        </form>
    </div>
</section>


{% endblock %}

templates/review-showcase.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>All Reviews for {{ album.album_name }}</h1>
    <ul class="album-list">
        {% if not reviews %}
            <h3>No reviews for this album</h3>
        {% else %}
            {% for review in reviews %}
                <li class="album-item">

                    <div class="album-details">
                        <h3>{{ review.description }}</h3>
                        <h3>Rating: {{ review.rating }} </h3>
                        <h3>Likes: {{ review.like_set.count }} Dislikes: {{ review.dislike_set.count }} </h3>
                        <!-- Display other album details here -->

                    </div>
                    <a href="{% url 'like-review' review.id%}">Like</a>
                    <a href="{% url 'dislike-review' review.id%}">Dislike</a>
                </li>
            {% endfor %}
        {% endif %}
    </ul>
    <!-- Display pagination links -->
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current-page">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

{% endblock %}